#!/bin/bash
#
# install.sh — build a fresh APK and install it on a connected Android device.
#
# Usage:
#   ./install.sh              # release build (standalone, no Metro needed) — default
#   ./install.sh dev          # debug build (requires Metro: npx expo start --dev-client)
#   ./install.sh --device ID  # target a specific device (see: adb devices)
#   ./install.sh --clean      # regenerate the native android project first (expo prebuild --clean)
#
# Notes:
#   - android/ is git-ignored and fully generated by expo prebuild. If the build
#     fails with "No variants exist" for react-native-* projects, the autolinking
#     is corrupted (e.g. after a node_modules reinstall) — re-run with --clean.
#
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ANDROID_DIR="${ROOT_DIR}/android"
BUILDS_DIR="${ROOT_DIR}/builds"

MODE="release"
DEVICE_ID=""
DO_CLEAN=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    dev|debug)        MODE="debug"; shift ;;
    prod|release)     MODE="release"; shift ;;
    -d|--device)      DEVICE_ID="${2:-}"; shift 2 ;;
    --clean)          DO_CLEAN=1; shift ;;
    -h|--help)        sed -n '3,15p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "Unknown argument: $1"; exit 1 ;;
  esac
done

if [[ "${MODE}" == "release" ]]; then
  BUILD_TASK="assembleRelease"
  APK_SRC="${ANDROID_DIR}/app/build/outputs/apk/release/app-release.apk"
else
  BUILD_TASK="assembleDebug"
  APK_SRC="${ANDROID_DIR}/app/build/outputs/apk/debug/app-debug.apk"
fi

command -v adb  >/dev/null 2>&1 || { echo "Error: adb not found (add Android platform-tools to PATH)."; exit 1; }
command -v node >/dev/null 2>&1 || { echo "Error: node not found."; exit 1; }

# Pin a Gradle-compatible JDK (Gradle 8.14 + Expo SDK 54 AGP -> Java 21/17).
if [[ -x /usr/libexec/java_home ]]; then
  for v in 21 17 23; do
    if JH="$(/usr/libexec/java_home -v "$v" 2>/dev/null)"; then export JAVA_HOME="$JH"; break; fi
  done
fi
echo "Using JAVA_HOME=${JAVA_HOME:-<system default>}"

# Resolve the Android package id from app.json.
PACKAGE_NAME="$(node -e "console.log(require('${ROOT_DIR}/app.json').expo.android.package)")"
[[ -n "${PACKAGE_NAME}" ]] || { echo "Error: Android package not found in app.json."; exit 1; }

# Regenerate the native project on request (fixes corrupted autolinking).
if [[ "${DO_CLEAN}" == "1" ]]; then
  echo "Regenerating native android project (expo prebuild --clean)..."
  (cd "${ROOT_DIR}" && npx expo prebuild --clean --platform android)
fi

# Prebuild the native project if it isn't there yet.
if [[ ! -d "${ANDROID_DIR}" ]]; then
  echo "Android project missing — running expo prebuild..."
  (cd "${ROOT_DIR}" && npx expo prebuild --platform android)
fi

# Ensure the Android SDK location is known (prebuild --clean wipes local.properties).
SDK_PATH="${ANDROID_HOME:-${ANDROID_SDK_ROOT:-}}"
[[ -z "${SDK_PATH}" && -d "/opt/homebrew/share/android-commandlinetools" ]] && SDK_PATH="/opt/homebrew/share/android-commandlinetools"
[[ -z "${SDK_PATH}" && -d "${HOME}/Library/Android/sdk" ]] && SDK_PATH="${HOME}/Library/Android/sdk"
if [[ ! -f "${ANDROID_DIR}/local.properties" && -n "${SDK_PATH}" ]]; then
  echo "sdk.dir=${SDK_PATH}" > "${ANDROID_DIR}/local.properties"
  echo "Wrote android/local.properties -> ${SDK_PATH}"
fi

echo "Building APK (${MODE})..."
(cd "${ANDROID_DIR}" && ./gradlew "${BUILD_TASK}")
[[ -f "${APK_SRC}" ]] || { echo "Error: APK not produced at ${APK_SRC}"; exit 1; }

# Keep a timestamped copy.
mkdir -p "${BUILDS_DIR}"
STAMP="$(node -e 'const d=new Date();const p=n=>String(n).padStart(2,"0");console.log(`${d.getFullYear()}${p(d.getMonth()+1)}${p(d.getDate())}-${p(d.getHours())}${p(d.getMinutes())}${p(d.getSeconds())}`)')"
APK_DEST="${BUILDS_DIR}/sgdv-${MODE}-${STAMP}.apk"
cp "${APK_SRC}" "${APK_DEST}"
echo "APK saved to: ${APK_DEST}"

# Pick a target device now that the APK exists.
if [[ -z "${DEVICE_ID}" ]]; then
  DEVICE_ID="$(adb devices | awk '$2=="device"{print $1; exit}')"
fi
if [[ -z "${DEVICE_ID}" ]]; then
  echo "Build done, but no device is connected — skipping install."
  echo "Connect a device (enable USB debugging) and run: adb install -r -d \"${APK_DEST}\""
  exit 0
fi
echo "Target device: ${DEVICE_ID}"

echo "Installing on ${DEVICE_ID}..."
adb -s "${DEVICE_ID}" wait-for-device
if ! adb -s "${DEVICE_ID}" install -r -d "${APK_DEST}"; then
  echo "Reinstall failed — uninstalling and retrying..."
  adb -s "${DEVICE_ID}" uninstall "${PACKAGE_NAME}" || true
  adb -s "${DEVICE_ID}" install "${APK_DEST}"
fi

echo "Launching ${PACKAGE_NAME}..."
adb -s "${DEVICE_ID}" shell monkey -p "${PACKAGE_NAME}" -c android.intent.category.LAUNCHER 1 >/dev/null 2>&1 || true

echo "Done."
[[ "${MODE}" == "debug" ]] && echo "Note: debug build needs Metro — run 'npx expo start --dev-client'."
exit 0
