const { withGradleProperties, withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * Persistent APK-size optimizations.
 *
 * `android/` is generated by `expo prebuild` and git-ignored, so any hand edits
 * to gradle.properties / proguard-rules.pro are lost on `--clean`. This plugin
 * re-applies the size settings on every prebuild:
 *
 *   1. reactNativeArchitectures = armeabi-v7a,arm64-v8a
 *      Drops the x86 / x86_64 ABIs (~47 MB of .so). Those are emulator-only —
 *      real Android phones are ARM, and the Apple-Silicon emulator runs arm64.
 *   2. android.enableMinifyInReleaseBuilds = true
 *      Turns on R8 so unused Java/Kotlin classes are stripped from the DEX.
 *   3. android.enableShrinkResourcesInReleaseBuilds = true
 *      Removes resources nothing references. Requires minify.
 *
 * It also re-asserts the R8 keep rules for React Native internals (Reanimated /
 * TurboModules) so enabling minify can't strip them after a clean prebuild.
 */
const SIZE_PROPS = {
  reactNativeArchitectures: 'armeabi-v7a,arm64-v8a',
  'android.enableMinifyInReleaseBuilds': 'true',
  'android.enableShrinkResourcesInReleaseBuilds': 'true',
};

const KEEP_MARKER = 'withApkSizeOptimizations keep rules';
const PROGUARD_KEEPS = `
# --- ${KEEP_MARKER} (do not remove) ---
# R8 is enabled for release; keep RN internals that are referenced reflectively.
-keep class com.swmansion.reanimated.** { *; }
-keep class com.facebook.react.turbomodule.** { *; }
# expo-modules-core loads this via AndroidManifest <meta-data> + Class.forName(),
# so R8 can't see the reference and would strip it (used by expo-task-manager
# headless background tasks). Keep the whole apploader package.
-keep class expo.modules.adapters.react.apploader.** { *; }
`;

const withSizeGradleProps = (config) =>
  withGradleProperties(config, (cfg) => {
    for (const [key, value] of Object.entries(SIZE_PROPS)) {
      const existing = cfg.modResults.find(
        (item) => item.type === 'property' && item.key === key,
      );
      if (existing) {
        existing.value = value;
      } else {
        cfg.modResults.push({ type: 'property', key, value });
      }
    }
    return cfg;
  });

const withSizeProguardKeeps = (config) =>
  withDangerousMod(config, [
    'android',
    (cfg) => {
      const file = path.join(
        cfg.modRequest.platformProjectRoot,
        'app',
        'proguard-rules.pro',
      );
      const contents = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : '';
      if (!contents.includes(KEEP_MARKER)) {
        fs.writeFileSync(file, `${contents}\n${PROGUARD_KEEPS}`);
      }
      return cfg;
    },
  ]);

module.exports = (config) => withSizeProguardKeeps(withSizeGradleProps(config));
