import { StyleSheet } from 'react-native';

/* Common styles for all screens */

export const appStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'flex-start',
    paddingTop: 60,
    paddingBottom: 20,
    paddingHorizontal: 20,
    backgroundColor: 'transparent',
  },
  titleContainer: {
    alignItems: 'center',
    flex: 1,
    paddingHorizontal: 16,
  },
  subtitle: {
    fontSize: 15.6,
    textAlign: 'center',
    marginTop: 8,
    fontWeight: '400',
    lineHeight: 21,
    paddingHorizontal: 0,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    paddingHorizontal: 10,
  },
  title: {
    fontSize: 28,
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: 8,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  sunEventText: {
    fontSize: 18,
    color: '#FFFFFF',
    textAlign: 'center',
    marginTop: 12,
    fontWeight: '500',
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  alarmOverlay: {
    flex: 1,
    backgroundColor: 'rgba(10, 10, 20, 0.92)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  alarmCard: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: '#16162a',
    borderRadius: 28,
    paddingVertical: 36,
    paddingHorizontal: 28,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 107, 53, 0.45)',
    shadowColor: '#FF6B35',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.45,
    shadowRadius: 24,
    elevation: 12,
  },
  alarmIconOuter: {
    width: 104,
    height: 104,
    borderRadius: 52,
    backgroundColor: 'rgba(255, 107, 53, 0.12)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  alarmIconInner: {
    width: 78,
    height: 78,
    borderRadius: 39,
    backgroundColor: 'rgba(255, 107, 53, 0.18)',
    borderWidth: 1.5,
    borderColor: 'rgba(255, 107, 53, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  alarmTime: {
    fontSize: 52,
    fontWeight: '700',
    color: '#FFFFFF',
    letterSpacing: 1,
  },
  alarmDate: {
    fontSize: 15,
    color: '#FFFFFF',
    opacity: 0.6,
    marginTop: 2,
    marginBottom: 18,
  },
  alarmTitle: {
    fontSize: 26,
    fontWeight: '700',
    color: '#FF6B35',
    marginBottom: 6,
  },
  alarmMessage: {
    fontSize: 16,
    color: '#FFFFFF',
    marginBottom: 28,
    opacity: 0.85,
    textAlign: 'center',
  },
  alarmButtonRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 14,
  },
  snoozeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 24,
    paddingVertical: 15,
    borderRadius: 30,
    borderWidth: 1.5,
    borderColor: '#FF6B35',
    backgroundColor: 'transparent',
  },
  snoozeButtonText: {
    fontSize: 17,
    fontWeight: '600',
    color: '#FF6B35',
  },
  stopAlarmButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#FF6B35',
    paddingHorizontal: 32,
    paddingVertical: 15,
    borderRadius: 30,
  },
  stopAlarmText: {
    fontSize: 17,
    fontWeight: '700',
    color: '#FFFFFF',
  },
});

