import { StyleSheet } from 'react-native';
import {
  SUN_COUNTDOWN_FONT_SIZE,
  SUN_COUNTDOWN_LABEL_FONT_SIZE,
  SUN_COUNTDOWN_LETTER_SPACING,
  SUN_TIME_CARD_MIN_WIDTH,
  SUN_TIME_CARD_BORDER_RADIUS,
  SUN_TIME_CARD_PADDING,
  SUN_TIME_LABEL_FONT_SIZE,
  SUN_TIME_VALUE_FONT_SIZE,
  SUN_CONTROLS_BORDER_RADIUS,
  SUN_CONTROLS_PADDING,
  SUN_SECTION_TITLE_FONT_SIZE,
  SUN_CONTROL_TEXT_FONT_SIZE,
  SUN_CONTROL_TEXT_NESTED_FONT_SIZE,
  SUN_TEST_BUTTON_BORDER_RADIUS,
  SUN_TEST_BUTTON_PADDING,
  SUN_SUNRISE_ICON_COLOR,
} from '../constants';

export const sunCycleViewStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 100,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 40,
  },
  loadingText: {
    fontSize: 16,
    color: '#FFFFFF',
    opacity: 0.7,
  },
  countdownContainer: {
    alignItems: 'center',
    marginBottom: 30,
  },
  countdownLabel: {
    fontSize: SUN_COUNTDOWN_LABEL_FONT_SIZE,
    color: '#FFFFFF',
    opacity: 0.8,
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  countdownTime: {
    fontSize: SUN_COUNTDOWN_FONT_SIZE,
    fontWeight: '700',
    color: '#FFFFFF',
    letterSpacing: SUN_COUNTDOWN_LETTER_SPACING,
  },
  countdownSubtext: {
    fontSize: 20,
    color: '#FFFFFF',
    opacity: 0.7,
    marginTop: 8,
  },
  timesContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 30,
  },
  timeCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: SUN_TIME_CARD_BORDER_RADIUS,
    padding: SUN_TIME_CARD_PADDING,
    minWidth: SUN_TIME_CARD_MIN_WIDTH,
  },
  timeLabel: {
    fontSize: SUN_TIME_LABEL_FONT_SIZE,
    color: '#FFFFFF',
    opacity: 0.7,
    marginTop: 8,
    marginBottom: 4,
  },
  timeValue: {
    fontSize: SUN_TIME_VALUE_FONT_SIZE,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  controlsContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: SUN_CONTROLS_BORDER_RADIUS,
    padding: SUN_CONTROLS_PADDING,
  },
  sectionTitle: {
    fontSize: SUN_SECTION_TITLE_FONT_SIZE,
    fontWeight: '600',
    color: '#FFFFFF',
    marginBottom: 16,
  },
  controlRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.1)',
  },
  controlRowSpaced: {
    marginTop: 16,
  },
  controlLabel: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    paddingRight: 8,
  },
  controlText: {
    fontSize: SUN_CONTROL_TEXT_FONT_SIZE,
    color: '#FFFFFF',
    marginLeft: 12,
    flexWrap: 'wrap',
    flex: 1,
  },
  controlTextNested: {
    fontSize: SUN_CONTROL_TEXT_NESTED_FONT_SIZE,
    color: '#FFFFFF',
    marginLeft: 12,
    opacity: 0.9,
    flexWrap: 'wrap',
    flex: 1,
  },
  nestedControls: {
    marginLeft: 20,
    paddingLeft: 16,
    borderLeftWidth: 2,
    borderLeftColor: 'rgba(253, 184, 19, 0.3)',
  },
  nestedControlsAlarm: {
    marginLeft: 20,
    paddingLeft: 16,
    borderLeftWidth: 2,
    borderLeftColor: 'rgba(255, 107, 53, 0.3)',
  },
  testButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FF6B35',
    borderRadius: SUN_TEST_BUTTON_BORDER_RADIUS,
    padding: SUN_TEST_BUTTON_PADDING,
    marginTop: 16,
  },
  scheduleAheadRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 16,
  },
  scheduleAheadLabel: {
    fontSize: 14,
    color: '#FFFFFF',
    opacity: 0.85,
  },
  scheduleAheadOptions: {
    flexDirection: 'row',
    gap: 8,
  },
  scheduleAheadChip: {
    minWidth: 44,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.25)',
    alignItems: 'center',
  },
  scheduleAheadChipActive: {
    backgroundColor: SUN_SUNRISE_ICON_COLOR,
    borderColor: SUN_SUNRISE_ICON_COLOR,
  },
  scheduleAheadChipText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
    opacity: 0.85,
  },
  scheduleAheadChipTextActive: {
    color: '#1a1a2e',
    opacity: 1,
  },
  infoBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(253, 184, 19, 0.1)',
    borderRadius: 8,
    padding: 12,
    marginTop: 16,
  },
  infoText: {
    fontSize: 14,
    color: '#FFFFFF',
    marginLeft: 8,
    flex: 1,
  },
  scheduledRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginTop: 8,
  },
  scheduledInfo: {
    flex: 1,
    paddingRight: 8,
  },
  scheduledTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  scheduledTime: {
    fontSize: 13,
    color: '#FFFFFF',
    opacity: 0.7,
    marginTop: 2,
  },
  scheduledRemove: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(220, 53, 69, 0.8)',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

